### ISSUE TITLE
how to upload it to arweave

### ISSUE THREAD

**Issue by AndreiD** [mul1sh/ar-auth#7]
hello,

thank you for creating this :) 
I have a problem when I try to build it and upload it to arweave
I run 
~~~~
npm run build
~~~~

that creates a dist directory

then I run 

~~~~
arweave deploy-dir ....
~~~~

the thing is, when I go to the generated link (after waiting for a new block) I get 

that some of the javascript resources are not found

https://arweave.net/RLvxXBw1louJ86aBifFdVQmPR2NShST316YXt63d3Mk

Request URL: https://24az3uearmbj.arweave.net/js/app.js
Request Method: GET
Status Code: 400 

as I know they are missing a "." in front of the upload script.

My question is, did you go into the build directory and manually added a "." in front of the js, css files ?

for example:
instead of 

~~~~
<link href=/css/app.css rel=preload as=style>
<link href=/js/app.js rel=preload as=script>
~~~~
you did

~~~~
<link href=./css/app.css rel=preload as=style>
<link href=./js/app.js rel=preload as=script>
~~~~

**Comment by mul1sh** [comment]
Hi, yes after running `npm run build` you still have to modify the `index.html` file in the `dist` folder to get rid of unnecessary deps i.e. for the favicons

And yes, you also have to modify it  the script tags

So instead of 

```html
<link href=/css/app.css rel=preload as=style>
<link href=/js/app.js rel=preload as=script>
```

You do 

```html
<link href="css/app.css" rel="stylesheet"/>
<script src="js/app.js" rel="stylesheet"/>
```

So that the index.html file ends up looking like this

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset=utf-8>
	<meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
	<title>AR AUTH</title>
	<meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0">
	<link href="css/app.css" rel="stylesheet"/>
	
</head>
<body>
	<div class=wrapper id=app></div>
	<script src="js/crypto.js"></script>
	<script src="js/app.js"></script>
</body>
</html>
```

And then finally you can run the command `arweave deploy-dir dist/` to upload the directory to arweave

**Comment by AndreiD** [comment]
thanks alot
